### ISSUE TITLE
Is there a version for psalm?

### ISSUE THREAD

**Issue by malukenho** [Roave/no-floaters#19]
May we have a version for psalm?

**Comment by Ocramius** [comment]
Hop on and help building it 😅

**Comment by ondrejmirtes** [comment]
My view on this is that people should use both Psalm and PHPStan. Both have enough unique features to justify it. So if people agree on this, there doesn't have to be a version of this package for Psalm.

**Comment by Ocramius** [comment]
Closing here: I think it's reasonable to leave this as a PHPStan-only package, while a psalm-equivalent would need a separate package.
